name: main

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: (cache) restore
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install
        run: bun install --frozen-lockfile

      - name: (coverage) Test
        run: bun test --coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
